### ISSUE TITLE
"along with" tagged differently in English EWT and English GUM

### ISSUE THREAD

**Issue by olesar** [UniversalDependencies/UD_English-GUM#1]
"along with" tagged differently in English EWT and English GUM (+ some inconsistency within GUM, see #2-6)
http://match.grew.fr/?custom=5b1e8480df1db&corpus=UD_English-EWT@2.2
http://match.grew.fr/?custom=5b1e857a5af2f&corpus=UD_English-GUM@2.2

**Comment by nschneid** [comment]
> http://match.grew.fr/?custom=5b1e8480df1db&corpus=UD_English-EWT@2.2
> http://match.grew.fr/?custom=5b1e857a5af2f&corpus=UD_English-GUM@2.2

This is a legitimate difference: the latter is the idiom "get along (with)".

In general, there needs to be an official policy on multiword prepositions, which "along with" arguably is in the first example: UniversalDependencies/docs#496

**Comment by amir-zeldes** [comment]
Thank you both - I agree, the GUM case is probably tagged as it should be, though it does illustrate the ambiguity of ADP for phrasal verb particles. In the original SD annotation it's clear, since this is RP and not IN:

https://github.com/amir-zeldes/gum/blob/master/dep/stanford/GUM_interview_gaming.conll10#L292

I also agree that the first case should be worked out under the MWE proposal, I'm not very happy with the double `case` analysis. For now I think this issue can be closed, right?
