### ISSUE TITLE
Tagging errors for "that"

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-GUM#13]
http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=604d1644b2f85&clustering=T.upos

This query shows 12 `SCONJ`, 10 `ADP`, 1 `DET`.

Compare EWT, which uses `ADV` for some cases but never `SCONJ` or `ADP`.

**Comment by amir-zeldes** [comment]
Thanks for reporting, fixed in 6c0cd45

DET and ADP should be gone, and I kept SCONJ only for the cases we discussed where "that" cannot be replaced by a "which" (i.e. it is like Heb. še, and not a pronoun, things like "places that I should go there" etc.)

**Comment by nschneid** [comment]
Are the SCONJ cases comparable to the ADV cases in EWT?

**Comment by amir-zeldes** [comment]
As far as I can see, not most of them... A few in EWT are clefts, which would have SCONJ in GUM:

  * it was on his nudging _that_ the Indians made conciliatory gestures toward Islamabad

Some are plain adnominal `acl`, this would be SCONJ as well for GUM, but it wouldn't be `acl:relcl`:

  * the same way _that_ an immediate sudden democracy did not work in Russia

But there is also some overlap, for example this one would be `acl:relcl` and SCONJ for "that" if it were in GUM:

  * That was the day _that_ GOD'S CURSE fell upon the world of Rock

The reason is that it is a relative clause specifying which day it was, but you can't replace "that" with "which" (maybe could have been "in which"). It's not as obvious a case as with a resumptive ("people that I should talk with them"), but based strictly on the substitution with "which" guideline, I could see this being the same SCONJ in GUM. 

In any case, ADV seems wrong to me in all of these.

**Comment by nschneid** [comment]
Ah. I don't have good intuitions about relative clauses but if you wanted to make EWT consistent with GUM (see also UniversalDependencies/UD_English-EWT#136), I wouldn't object!

**Comment by amir-zeldes** [comment]
Well, I'm not sure who it is that needs to object or not for EWT... It's not really our IP to change freely. I do want there to be fewer inconsistencies, but it feels kind of futile, because there is no real prospect of getting the corpora to converge - I'd devote some time to it if people told me 'feel free to redo everything in EWT like GUM' (or told me specific things they wanted to see changed in GUM, in which case I would consider doing the opposite). 

If that were the situation, I'd run some parsers trained on GUM to predict on EWT, find the main recurring differences, and organize a hackathon or something to do this once and for all. But my feeling is I really don't have a mandate to do that, so I'm focusing on getting GUM as internally consistent as possible, and from the parsing perspective, using EWT model outputs as a feature for NLP on new GUM data (this is one of the things we did for the Amalgum paper, same way we used OntoNotes xpos).
