### ISSUE TITLE
Minspan index ignores empty nodes

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/UD_English-GUM#85]
Zero mentions is defined as a mention whose head is an empty node. Thus there must be a way how to annotate an empty node as a head in CorefUD. So when computing a head index, we include all nodes, including the empty nodes. I am not sure if we want the definition of `minspan` in UD_English-GUM to differ from the definition of `head` in CorefUD_English-GUM even in such technical details. If not, `minspan` should also count all nodes within the span. However, it seems that currently empty nodes are ignored in UD_English-GUM when computing the `minspan` index.

In GUM_textbook_labor-19, there is a mention of entity `97` and it seems that its `minspan` should be word 14 ("products"), which is the 6th word of the span, but the annotation says minspan=5:

```CoNLL-U
10      one     one     NUM     CD      NumForm=Word|NumType=Card       14      nummod  14:nummod       Entity=(97-abstract-new-cf4-5-sgl
10.1    product _       _       _       _       _       _       8:obl:on|17:nsubj|21:nsubj:xsubj        CopyOf=-1
11      or      or      CCONJ   CC      _       13      cc      14:cc   _
12      a       a       DET     DT      Definite=Ind|PronType=Art       13      orphan  14:det  _
13      few     few     ADJ     JJ      Degree=Pos      10      conj    14:amod _
14      products        product NOUN    NNS     Number=Plur     8       obl     8:obl:on|10.1:conj:or|17:nsubj|21:nsubj:xsubj   MSeg=produc-t-s
15      (       (       PUNCT   -LRB-   _       17      punct   17:punct        Discourse=elaboration-attribute:57->56:0:syn-mdf-443+grf-prn-444,452+syn-nmn-446|SpaceAfter=No
16      sometimes       sometimes       ADV     RB      _       17      advmod  17:advmod       MSeg=sometime-s
17      called  call    VERB    VBN     Tense=Past|VerbForm=Part|Voice=Pass     14      acl     14:acl  MSeg=call-ed
18      its     its     PRON    PRP$    Case=Gen|Gender=Neut|Number=Sing|Person=3|Poss=Yes|PronType=Prs 21      nmod:poss       21:nmod:poss    Entity=(98-abstract-new-cf5-4-sgl(96-organization-giv:act-cf1-1-ana)|MSeg=it-s
19      “       ''      PUNCT   ``      _       21      punct   21:punct        SpaceAfter=No|XML=<q>
20      core    core    NOUN    NN      Number=Sing     21      compound        21:compound     _
21      competency      competency      NOUN    NN      Number=Sing     17      xcomp   17:xcomp        MSeg=competen-cy|SpaceAfter=No
22      ”       ''      PUNCT   ''      _       21      punct   21:punct        Entity=98)|SpaceAfter=No|XML=</q>
23      )       )       PUNCT   -RRB-   _       17      punct   17:punct        Entity=97)96)
```

In CorefUD, the head is identified as 10.1 ("product") and I think it is correct because it is a conjunction (one product or few products), so the head should be the first conjunct. So another (closely related) question is whether also the `minspan` should not be the empty node.

So what are the guidelines for `minspan`? Can it ever be an empty node? If not, what should be the `minspan` of a pro-drop pronoun in a pro-drop language?

**Comment by amir-zeldes** [comment]
Thanks for bringing this up, it's an interesting point to consider. Obviously it would be possible to consider minspans in the numbering of tokens in the actual minspans, but I cannot imagine a situation in which I would want an empty node to actually be part of the minspan (which is indeed not the same as head). 

I think there are two issues with allowing empty nodes as minspans: a technical one and a theoretical one. The theoretical issue is whether it makes sense for a hypothetical node, whose position or even existence are not really certain in pre-theoretical terms, to be a necessary anchor point for a mention. The practical issue is that corpora can be converted into many formats, including ones that do not represent empty nodes (in fact, most source formats for GUM's native upstream repo do not, including the format in which coref annotations originate). In other words, we would be creating an incompatibility with many of the tools that generate coref annotations (since they may not be able to annotate empty string tokens well, and the existence of these tokens pre-supposes a syntactic analysis), and an incompatibility with tools which could previously easily interpret conversions of minspan 'as is', but would now need to be updated to check for empty nodes before performing a conversion.

None of that means it's impossible to consider virtual node positions in minspans, but it would create some more chaos, so we should think hard whether this is necessary. A possible alternative, if we think that empty nodes cannot be members of minspan, is to say that zero anaphors have no minspan, since they have no textual presence; if someone wants to know the 'main token' of such a mention in a format that expresses zeros, then it would trivially be that zero token, which a zero-aware tool should be able to handle anyway.

**Comment by martinpopel** [comment]
> incompatibility with tools which could previously easily interpret conversions of minspan 'as is'

It is questionable what "as is" means, but if the tools don't see the empty nodes (because they are not CoNLL-U compatible) then I agree. This is a fair point.

> if someone wants to know the 'main token' of such a mention

There are datasets in CorefUD where zero mentions have multiple empty nodes, so it is not so "trivial" to say which one is the main one. But we have the `head` attribute for this purpose, so I don't need to change the semantics of `minspan` if there is no one who would benefit from it.
As you say `minspan` and `head` are indeed not the same thing (minspan can include multiple words; head in CorefUD is always the "highest" node according to the syntactic tree, despite there are some [edge cases](https://github.com/udapi/udapi-python/blob/master/udapi/block/corefud/movehead.py)).
The fact that `minspan` can never include an empty node and thus zero mentions cannot have any `minspan` is just another difference between `minspan` and `head`.

So I am closing this issue. (This is what I expected. I just wanted to make sure it is also your intention.)
