### ISSUE TITLE
Is entity ID guaranteed to be unique within the whole CoNLL-U file?

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/UD_English-GUM#9]
When loading `en_gum-ud-dev.conllu`, I found 262 mentions of `person-4` in 8 documents (marked with `# newdoc id`).
It seems `person-4` is a different entity in each of the documents, as it refers to e.g. "Michiel Cock" in GUM_academic_librarians, "Kendra" in GUM_conversation_grounded, etc.
So the entity ID does no seem to be unique within the CoNLL-U file.
Is this a feature or a bug?

**Comment by nschneid** [comment]
From the README it sounds like they are supposed to be unique *per document*, not in the entire corpus or file (i.e. there is no cross-document coreference info).

**Comment by martinpopel** [comment]
My two cents (feel free to ignore it, I have already fixed the data for my own purposes anyway).

>  they are supposed to be unique *per document*

If this is really the case, there should be an explicit warning in the README (`sent_id` *must* be unique within the whole file, so users may expect the same from entity IDs).
I think it would be beneficial for the users to make the ID unique per file. In future, it may allow e.g. to put each chapter of a book into its own document, but be able to annotate cross-document coreference.

**Comment by amir-zeldes** [comment]
That is correct, entity IDs are unique per document, not per partition. This is for the same reason conllu+ requires headers to be repeated in each file: so that concatenation of documents in whatever constellation will remain valid. We also need to keep in mind that the GUMReddit dataset is basically generated from the same sources in the origin repo and the UD separation into two TBs with separate files is kind of artificial. The annotation interface we use for coref is also per-document, so we don't have the book chapter scenario you mentioned.

That said, there is some amount of cross-document coref using Wikification labels which are propagated in the coref layer, including to pronouns. For example, Noam Chomsky is mentioned and labeled: 
o	[Here](https://github.com/amir-zeldes/gum/blob/master/dep/GUM_bio_fillmore.conllu#L286) in a biography of Chuck Fillmore (notice the identifier Noam_Chomsky in the last column)
o	[Here](https://github.com/amir-zeldes/gum/blob/master/dep/GUM_interview_chomsky.conllu#L12) in an interview by somebody else (this is a different document, same identifier is used)
o	And [here](https://github.com/amir-zeldes/gum/blob/master/dep/GUM_interview_chomsky.conllu#L227) in an utterance he makes as “I”

So for wikified entities, the Wiki link part of the identifier can be used for inter-document coreference.
